name: GitHub Actions Demo
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
      # チェックアウト
      # ライブラリのロード（キャッシュのロード）
      # lockfileのチェック
  check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: exit 0
      # prittier
      # lint
  conslusion:
    if: always()
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v1
      - run: |
          echo "let's see the workflow conclusion"
          echo ${{ env.WORKFLOW_CONCLUSION }}
  
