name: GitHub Actions Demo
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
      # チェックアウト
      # ライブラリのロード（キャッシュのロード）
      # lockfileのチェック
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
      # prittier
      # lint
  conslusion:
    if: always()
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "let's see the workflow conclusion"
          echo ${{ env.WORKFLOW_CONCLUSION }}
  
